version: '3.8'

services:
  apuntecadigital-backend:
    build:
      context: .
      dockerfile: src/ApuntecaDigital.Backend.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=apuntecadigital.backend;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;
      - ConnectionStrings__SqliteConnection=Data Source=/app/data/database.sqlite
    volumes:
      - apuntecadigital-data:/app/data
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 3s

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  apuntecadigital-data:
  sqlserver-data: